In [23]:
import numpy as np
import opencv as cv

a = np.array([1,1,1])
b = np.array([2,2,2])

c = []
c.append(a)
c.append(b)


d = np.array([3,3,3])
e = np.array([4,4,4])

f = []
f.append(d)
f.append(e)

j = []
j.append(c)
j.append(f)
j = np.array(j)

print (j)
print (np.shape(j))

rgb = np.dstack((a,b,c))

j.reshape(3,2,2)

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]
(2, 2, 3)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 2 has size 2

In [22]:
from PIL import Image
import numpy as np
rgbArray = np.zeros((512,512,3), 'uint8')
rgbArray[..., 0] = a*256
rgbArray[..., 1] = g*256
rgbArray[..., 2] = b*256
img = Image.fromarray(rgbArray)
img.save('myimg.jpeg')

NameError: name 'r' is not defined