In [19]:
import numpy as np

a = np.array([1,1,1])
b = np.array([2,2,2])

c = []
c.append(a)
c.append(b)


d = np.array([3,3,3])
e = np.array([4,4,4])

f = []
f.append(d)
f.append(e)

j = []
j.append(c)
j.append(f)
j = np.array(j)

print (j)
print (np.shape(j))

rgb = np.dstack((a,b,c)()

j.reshape(3,2,2)

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]
(2, 2, 3)


TypeError: dstack() takes 1 positional argument but 3 were given